ci: use chrome browser instead of electron (#3409)
## Description

We've been having more and more instances of 

```
Timed out waiting for the browser to connect. Retrying... 
Target.getTargets will not run as browser CRI connection was reset 
Error: Target.getTargets will not run as browser CRI connection was reset at c.send (<embedded>:2743:68062) at async v._onAttachToTarget (<embedded>:2743:185108) at async EventEmitter.<anonymous> (<embedded>:2743:183801) 
ERR_FAILED (-2) loading 'about:blank' Error: ERR_FAILED (-2) loading 'about:blank' at rejectAndCleanup (node:electron/js2c/browser_init:2:80969) at finishListener (node:electron/js2c/browser_init:2:81131) at WebContents.stopLoadingListener (node:electron/js2c/browser_init:2:81518) at WebContents.emit (node:events:530:35)
```

the 🤖 says try using chrome instead